name: Checks

on: [pull_request]
# on: [push] # just for testing

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change Directory to Server
        run: cd server
      - name: Test
        run: |
          cd server
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # - name: Lint
      #   run: |
      #     cd server
      #     docker-compose run --rm app sh -c "flake8"
